### ISSUE TITLE
Password transmission question?

### ISSUE THREAD

**Issue by nocmt** [gslender/get_secure_storage#2]
I have a question:

I added the password in this line of code: await GetSecureStorage.init(password: "123"); 

Does it mean "GetSecureStorage() == GetSecureStorage(password: "123")" ?

I tested and found it to be equal, but I want to get a response from the developer.

**Comment by gslender** [comment]
The object instance of the class will be equal but the read/write of the items will be incorrect as password used are different.

Equality of a class object doesn't account for things like the value of a transient variable such as the password
