### ISSUE TITLE
Data doesn't encrypted. 

### ISSUE THREAD

**Issue by eyyubzademireli** [gslender/get_secure_storage#3]
When I write data. Then open it in android studio 'GetSecureStorage.bak' I see salt data.

**Comment by gslender** [comment]
Write a test that demonstrates what you're doing

**Comment by eyyubzademireli** [comment]
![carbon (1)](https://github.com/gslender/get_secure_storage/assets/5758775/215e5f52-351b-494e-aaf9-d7ba6ba41214)

**Comment by eyyubzademireli** [comment]
this is my service. And I use write method. My data was written. but not encrypted.

**Comment by gslender** [comment]
This isn't a test, but an example of how you used the library - that doesn't prove anything 

What were the results of the bak file and what were you expecting it to be etc?

Eg Why are you suggesting it's incorrect?

**Comment by gslender** [comment]
Also, if the Pwd is null it won't encrypt the contents. So I can't confirm your test as your password you are using might be null

That's why you should have a test that works irrespective of your code

**Comment by eyyubzademireli** [comment]
I'm so sorry. It's my bad. dotenv.env['password'] must bu capitalcase -> PASSWORD. I'm sorry. Please close this issue.
