### ISSUE TITLE
Not able to build release version web

### ISSUE THREAD

**Issue by Bikram40** [gslender/get_secure_storage#4]
main.dart.js?v=420536051:6234 Uncaught minified:afq: SecretBox has wrong message authentication code (MAC)

**Comment by gslender** [comment]
What the simplest test example that demonstrates this bug/error?

**Comment by gslender** [comment]
Also, without specific details around what Flutter version, what OS or what browser, I won't necessarily be able to reproduce either

**Comment by Bikram40** [comment]
When I built a web-release version using Flutter 3.16.9 and ran it on the Chrome browser, it gave an error. I think this is coming from https://pub.dev/packages/cryptography.

**Comment by Bikram40** [comment]
This issue is coming on when I already once build release version of web and run it on chrome and again build with different password. After "clear site data" from chrome `application->storage ` It is working !!.
But I think there is a issue with this line 
lib/src/storage_impl.dart
`import 'sdk/flutter.dart' if (dart.library.ui) 'platform/dart.dart';`
This should be 
`import 'sdk/flutter.dart' if (dart.library.ui) 'sdk/dart.dart';`

**Comment by gslender** [comment]
No, this is working correctly as designed. You need to catch the exemption with a try/catch and handle the condition of what to do if the password is incorrect. The error is saying exactly what is wrong - the secret (SecretBox) is incorrect (has the wrong code) from what was stored (encrypted into the storage) and cannot read/used.

**Comment by gslender** [comment]
Have updated package to support later versions of Flutter
